//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdobeSign.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdobeSign.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads a document and obtains the document&apos;s ID..
        /// </summary>
        public static string AddDocument_Description {
            get {
                return ResourceManager.GetString("AddDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Document.
        /// </summary>
        public static string AddDocument_DisplayName {
            get {
                return ResourceManager.GetString("AddDocument_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file part of the multipart request for document upload. You can upload only one file at a time..
        /// </summary>
        public static string AddDocument_FilePath_Description {
            get {
                return ResourceManager.GetString("AddDocument_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string AddDocument_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("AddDocument_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique identifier of the uploaded document that can be used in an agreement..
        /// </summary>
        public static string AddDocument_TransientDocumentId_Description {
            get {
                return ResourceManager.GetString("AddDocument_TransientDocumentId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transient Document Id.
        /// </summary>
        public static string AddDocument_TransientDocumentId_DisplayName {
            get {
                return ResourceManager.GetString("AddDocument_TransientDocumentId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the api_access_point here generated by browser call..
        /// </summary>
        public static string AdobeSignScope_APIAccessPoint_Description {
            get {
                return ResourceManager.GetString("AdobeSignScope_APIAccessPoint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Access Point.
        /// </summary>
        public static string AdobeSignScope_APIAccessPoint_DisplayName {
            get {
                return ResourceManager.GetString("AdobeSignScope_APIAccessPoint_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the application id of the adobe application..
        /// </summary>
        public static string AdobeSignScope_ClientId_Description {
            get {
                return ResourceManager.GetString("AdobeSignScope_ClientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id.
        /// </summary>
        public static string AdobeSignScope_ClientId_DisplayName {
            get {
                return ResourceManager.GetString("AdobeSignScope_ClientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the client secret id of the adobe application..
        /// </summary>
        public static string AdobeSignScope_ClientSecret_Description {
            get {
                return ResourceManager.GetString("AdobeSignScope_ClientSecret_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret.
        /// </summary>
        public static string AdobeSignScope_ClientSecret_DisplayName {
            get {
                return ResourceManager.GetString("AdobeSignScope_ClientSecret_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the scope activity to provide authentication for using other adobe sign activities..
        /// </summary>
        public static string AdobeSignScope_Description {
            get {
                return ResourceManager.GetString("AdobeSignScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe Sign Scope.
        /// </summary>
        public static string AdobeSignScope_DisplayName {
            get {
                return ResourceManager.GetString("AdobeSignScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is redirecting Uri of the adobe application..
        /// </summary>
        public static string AdobeSignScope_RedirectUri_Description {
            get {
                return ResourceManager.GetString("AdobeSignScope_RedirectUri_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect Uri.
        /// </summary>
        public static string AdobeSignScope_RedirectUri_DisplayName {
            get {
                return ResourceManager.GetString("AdobeSignScope_RedirectUri_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the token generated by Get Refresh Token activity..
        /// </summary>
        public static string AdobeSignScope_RefreshToken_Description {
            get {
                return ResourceManager.GetString("AdobeSignScope_RefreshToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token.
        /// </summary>
        public static string AdobeSignScope_RefreshToken_DisplayName {
            get {
                return ResourceManager.GetString("AdobeSignScope_RefreshToken_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agreement identifier, as returned by the agreement creation API or retrieved from the API to fetch agreements..
        /// </summary>
        public static string DeleteAgreement_AgreementId_Description {
            get {
                return ResourceManager.GetString("DeleteAgreement_AgreementId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Id.
        /// </summary>
        public static string DeleteAgreement_AgreementId_DisplayName {
            get {
                return ResourceManager.GetString("DeleteAgreement_AgreementId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the agreement..
        /// </summary>
        public static string DeleteAgreement_Description {
            get {
                return ResourceManager.GetString("DeleteAgreement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Agreement.
        /// </summary>
        public static string DeleteAgreement_DisplayName {
            get {
                return ResourceManager.GetString("DeleteAgreement_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Boolean..
        /// </summary>
        public static string DeleteAgreement_Response_Description {
            get {
                return ResourceManager.GetString("DeleteAgreement_Response_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string DeleteAgreement_Response_DisplayName {
            get {
                return ResourceManager.GetString("DeleteAgreement_Response_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agreement identifier, as returned by the agreement creation API or retrieved from the API to fetch agreements..
        /// </summary>
        public static string DownloadAgreement_AgreementId_Description {
            get {
                return ResourceManager.GetString("DownloadAgreement_AgreementId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Id.
        /// </summary>
        public static string DownloadAgreement_AgreementId_DisplayName {
            get {
                return ResourceManager.GetString("DownloadAgreement_AgreementId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and save the agreement..
        /// </summary>
        public static string DownloadAgreement_Description {
            get {
                return ResourceManager.GetString("DownloadAgreement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Agreement.
        /// </summary>
        public static string DownloadAgreement_DisplayName {
            get {
                return ResourceManager.GetString("DownloadAgreement_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide name of the file..
        /// </summary>
        public static string DownloadAgreement_FileName_Description {
            get {
                return ResourceManager.GetString("DownloadAgreement_FileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string DownloadAgreement_FileName_DisplayName {
            get {
                return ResourceManager.GetString("DownloadAgreement_FileName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the file path, where you want to save the file..
        /// </summary>
        public static string DownloadAgreement_FilePath_Description {
            get {
                return ResourceManager.GetString("DownloadAgreement_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string DownloadAgreement_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("DownloadAgreement_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Boolean..
        /// </summary>
        public static string DownloadAgreement_Response_Description {
            get {
                return ResourceManager.GetString("DownloadAgreement_Response_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string DownloadAgreement_Response_DisplayName {
            get {
                return ResourceManager.GetString("DownloadAgreement_Response_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetAccountInformation_Account_Description {
            get {
                return ResourceManager.GetString("GetAccountInformation_Account_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string GetAccountInformation_Account_DisplayName {
            get {
                return ResourceManager.GetString("GetAccountInformation_Account_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account identifier..
        /// </summary>
        public static string GetAccountInformation_AccountId_Description {
            get {
                return ResourceManager.GetString("GetAccountInformation_AccountId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Id.
        /// </summary>
        public static string GetAccountInformation_AccountId_DisplayName {
            get {
                return ResourceManager.GetString("GetAccountInformation_AccountId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves the information for an account..
        /// </summary>
        public static string GetAccountInformation_Description {
            get {
                return ResourceManager.GetString("GetAccountInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Account Information.
        /// </summary>
        public static string GetAccountInformation_DisplayName {
            get {
                return ResourceManager.GetString("GetAccountInformation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agreement identifier, as returned by the Send Document activity..
        /// </summary>
        public static string GetAgreement_AgreementId_Description {
            get {
                return ResourceManager.GetString("GetAgreement_AgreementId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Id.
        /// </summary>
        public static string GetAgreement_AgreementId_DisplayName {
            get {
                return ResourceManager.GetString("GetAgreement_AgreementId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetAgreement_AgreementInformation_Description {
            get {
                return ResourceManager.GetString("GetAgreement_AgreementInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Information.
        /// </summary>
        public static string GetAgreement_AgreementInformation_DisplayName {
            get {
                return ResourceManager.GetString("GetAgreement_AgreementInformation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves the current status of an agreement..
        /// </summary>
        public static string GetAgreement_Description {
            get {
                return ResourceManager.GetString("GetAgreement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Agreement.
        /// </summary>
        public static string GetAgreement_DisplayName {
            get {
                return ResourceManager.GetString("GetAgreement_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves agreements for the user..
        /// </summary>
        public static string GetAgreements_Description {
            get {
                return ResourceManager.GetString("GetAgreements_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Agreements.
        /// </summary>
        public static string GetAgreements_DisplayName {
            get {
                return ResourceManager.GetString("GetAgreements_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetAgreements_UserAgreements_Description {
            get {
                return ResourceManager.GetString("GetAgreements_UserAgreements_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAgreements.
        /// </summary>
        public static string GetAgreements_UserAgreements_DisplayName {
            get {
                return ResourceManager.GetString("GetAgreements_UserAgreements_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all the groups in an account..
        /// </summary>
        public static string GetAllGroups_Description {
            get {
                return ResourceManager.GetString("GetAllGroups_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All Groups.
        /// </summary>
        public static string GetAllGroups_DisplayName {
            get {
                return ResourceManager.GetString("GetAllGroups_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetAllGroups_GroupsInformation_Description {
            get {
                return ResourceManager.GetString("GetAllGroups_GroupsInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups Information.
        /// </summary>
        public static string GetAllGroups_GroupsInformation_DisplayName {
            get {
                return ResourceManager.GetString("GetAllGroups_GroupsInformation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get library documents for a user..
        /// </summary>
        public static string GetAllLibraryDocuments_Description {
            get {
                return ResourceManager.GetString("GetAllLibraryDocuments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All Library Documents.
        /// </summary>
        public static string GetAllLibraryDocuments_DisplayName {
            get {
                return ResourceManager.GetString("GetAllLibraryDocuments_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetAllLibraryDocuments_LibraryDocuments_Description {
            get {
                return ResourceManager.GetString("GetAllLibraryDocuments_LibraryDocuments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Documents.
        /// </summary>
        public static string GetAllLibraryDocuments_LibraryDocuments_DisplayName {
            get {
                return ResourceManager.GetString("GetAllLibraryDocuments_LibraryDocuments_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all the users..
        /// </summary>
        public static string GetAllUsers_Description {
            get {
                return ResourceManager.GetString("GetAllUsers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All Users.
        /// </summary>
        public static string GetAllUsers_DisplayName {
            get {
                return ResourceManager.GetString("GetAllUsers_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetAllUsers_UsersInformation_Description {
            get {
                return ResourceManager.GetString("GetAllUsers_UsersInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Information.
        /// </summary>
        public static string GetAllUsers_UsersInformation_DisplayName {
            get {
                return ResourceManager.GetString("GetAllUsers_UsersInformation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get workflows for a user..
        /// </summary>
        public static string GetAllWorkflows_Description {
            get {
                return ResourceManager.GetString("GetAllWorkflows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get All Workflows.
        /// </summary>
        public static string GetAllWorkflows_DisplayName {
            get {
                return ResourceManager.GetString("GetAllWorkflows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetAllWorkflows_Workflows_Description {
            get {
                return ResourceManager.GetString("GetAllWorkflows_Workflows_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflows.
        /// </summary>
        public static string GetAllWorkflows_Workflows_DisplayName {
            get {
                return ResourceManager.GetString("GetAllWorkflows_Workflows_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get detailed information about the group. .
        /// </summary>
        public static string GetGroup_Description {
            get {
                return ResourceManager.GetString("GetGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetGroup_DetailedGroupInformation_Description {
            get {
                return ResourceManager.GetString("GetGroup_DetailedGroupInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Group Information.
        /// </summary>
        public static string GetGroup_DetailedGroupInformation_DisplayName {
            get {
                return ResourceManager.GetString("GetGroup_DetailedGroupInformation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Group.
        /// </summary>
        public static string GetGroup_DisplayName {
            get {
                return ResourceManager.GetString("GetGroup_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group identifier, as returned by the group creation API or retrieved from the API to fetch groups..
        /// </summary>
        public static string GetGroup_GroupId_Description {
            get {
                return ResourceManager.GetString("GetGroup_GroupId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Id.
        /// </summary>
        public static string GetGroup_GroupId_DisplayName {
            get {
                return ResourceManager.GetString("GetGroup_GroupId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the user&apos;s associated with groups..
        /// </summary>
        public static string GetGroupsOfUser_Description {
            get {
                return ResourceManager.GetString("GetGroupsOfUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Groups Of User.
        /// </summary>
        public static string GetGroupsOfUser_DisplayName {
            get {
                return ResourceManager.GetString("GetGroupsOfUser_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetGroupsOfUser_UserGroupsInformation_Description {
            get {
                return ResourceManager.GetString("GetGroupsOfUser_UserGroupsInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups Information.
        /// </summary>
        public static string GetGroupsOfUser_UserGroupsInformation_DisplayName {
            get {
                return ResourceManager.GetString("GetGroupsOfUser_UserGroupsInformation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id of an user..
        /// </summary>
        public static string GetGroupsOfUser_UserId_Description {
            get {
                return ResourceManager.GetString("GetGroupsOfUser_UserId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string GetGroupsOfUser_UserId_DisplayName {
            get {
                return ResourceManager.GetString("GetGroupsOfUser_UserId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the details of a library document..
        /// </summary>
        public static string GetLibraryDocument_Description {
            get {
                return ResourceManager.GetString("GetLibraryDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Library Document.
        /// </summary>
        public static string GetLibraryDocument_DisplayName {
            get {
                return ResourceManager.GetString("GetLibraryDocument_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document identifier, as retrieved from the API to fetch library documents..
        /// </summary>
        public static string GetLibraryDocument_LibraryDocumentId_Description {
            get {
                return ResourceManager.GetString("GetLibraryDocument_LibraryDocumentId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Document Id.
        /// </summary>
        public static string GetLibraryDocument_LibraryDocumentId_DisplayName {
            get {
                return ResourceManager.GetString("GetLibraryDocument_LibraryDocumentId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetLibraryDocument_LibraryDocumentInformation_Description {
            get {
                return ResourceManager.GetString("GetLibraryDocument_LibraryDocumentInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Document Information.
        /// </summary>
        public static string GetLibraryDocument_LibraryDocumentInformation_DisplayName {
            get {
                return ResourceManager.GetString("GetLibraryDocument_LibraryDocumentInformation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves a list of message templates applicable to the current user..
        /// </summary>
        public static string GetMessageTemplates_Description {
            get {
                return ResourceManager.GetString("GetMessageTemplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Message Templates.
        /// </summary>
        public static string GetMessageTemplates_DisplayName {
            get {
                return ResourceManager.GetString("GetMessageTemplates_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message template locale. (Ex. en_US).
        /// </summary>
        public static string GetMessageTemplates_Locale_Description {
            get {
                return ResourceManager.GetString("GetMessageTemplates_Locale_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        public static string GetMessageTemplates_Locale_DisplayName {
            get {
                return ResourceManager.GetString("GetMessageTemplates_Locale_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetMessageTemplates_MessageTemplates_Description {
            get {
                return ResourceManager.GetString("GetMessageTemplates_MessageTemplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Templates.
        /// </summary>
        public static string GetMessageTemplates_MessageTemplates_DisplayName {
            get {
                return ResourceManager.GetString("GetMessageTemplates_MessageTemplates_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the api_access_point here generated by browser call..
        /// </summary>
        public static string GetRefreshToken_APIAccessPoint_Description {
            get {
                return ResourceManager.GetString("GetRefreshToken_APIAccessPoint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Access Point.
        /// </summary>
        public static string GetRefreshToken_APIAccessPoint_DisplayName {
            get {
                return ResourceManager.GetString("GetRefreshToken_APIAccessPoint_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the code generated by browser call..
        /// </summary>
        public static string GetRefreshToken_AuthorizationCode_Description {
            get {
                return ResourceManager.GetString("GetRefreshToken_AuthorizationCode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Code.
        /// </summary>
        public static string GetRefreshToken_AuthorizationCode_DisplayName {
            get {
                return ResourceManager.GetString("GetRefreshToken_AuthorizationCode_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the application id of the adobe application..
        /// </summary>
        public static string GetRefreshToken_ClientId_Description {
            get {
                return ResourceManager.GetString("GetRefreshToken_ClientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Id.
        /// </summary>
        public static string GetRefreshToken_ClientId_DisplayName {
            get {
                return ResourceManager.GetString("GetRefreshToken_ClientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the client secret id of the adobe application..
        /// </summary>
        public static string GetRefreshToken_ClientSecret_Description {
            get {
                return ResourceManager.GetString("GetRefreshToken_ClientSecret_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret.
        /// </summary>
        public static string GetRefreshToken_ClientSecret_DisplayName {
            get {
                return ResourceManager.GetString("GetRefreshToken_ClientSecret_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity is used to get the refresh token..
        /// </summary>
        public static string GetRefreshToken_Description {
            get {
                return ResourceManager.GetString("GetRefreshToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Refresh Token.
        /// </summary>
        public static string GetRefreshToken_DisplayName {
            get {
                return ResourceManager.GetString("GetRefreshToken_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is redirecting Uri of the adobe application..
        /// </summary>
        public static string GetRefreshToken_RedirectUri_Description {
            get {
                return ResourceManager.GetString("GetRefreshToken_RedirectUri_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect Uri.
        /// </summary>
        public static string GetRefreshToken_RedirectUri_DisplayName {
            get {
                return ResourceManager.GetString("GetRefreshToken_RedirectUri_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Refresh token will be used to pass in adobe sign scope activity..
        /// </summary>
        public static string GetRefreshToken_RefreshToken_Description {
            get {
                return ResourceManager.GetString("GetRefreshToken_RefreshToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Token.
        /// </summary>
        public static string GetRefreshToken_RefreshToken_DisplayName {
            get {
                return ResourceManager.GetString("GetRefreshToken_RefreshToken_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agreement identifier, as returned by the agreement creation API or retrieved from the API to fetch agreements..
        /// </summary>
        public static string GetSigningURL_AgreementId_Description {
            get {
                return ResourceManager.GetString("GetSigningURL_AgreementId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Id.
        /// </summary>
        public static string GetSigningURL_AgreementId_DisplayName {
            get {
                return ResourceManager.GetString("GetSigningURL_AgreementId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves the URL for the e-sign page for the current signer(s) of an agreement..
        /// </summary>
        public static string GetSigningURL_Description {
            get {
                return ResourceManager.GetString("GetSigningURL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Signing URL.
        /// </summary>
        public static string GetSigningURL_DisplayName {
            get {
                return ResourceManager.GetString("GetSigningURL_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetSigningURL_SigningUrlResponse_Description {
            get {
                return ResourceManager.GetString("GetSigningURL_SigningUrlResponse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing Url Response.
        /// </summary>
        public static string GetSigningURL_SigningUrlResponse_DisplayName {
            get {
                return ResourceManager.GetString("GetSigningURL_SigningUrlResponse_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the detailed information about the user in the caller account..
        /// </summary>
        public static string GetUser_Description {
            get {
                return ResourceManager.GetString("GetUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetUser_DetailedUserInformation_Description {
            get {
                return ResourceManager.GetString("GetUser_DetailedUserInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed User Information.
        /// </summary>
        public static string GetUser_DetailedUserInformation_DisplayName {
            get {
                return ResourceManager.GetString("GetUser_DetailedUserInformation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get User.
        /// </summary>
        public static string GetUser_DisplayName {
            get {
                return ResourceManager.GetString("GetUser_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id of an user..
        /// </summary>
        public static string GetUser_UserId_Description {
            get {
                return ResourceManager.GetString("GetUser_UserId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string GetUser_UserId_DisplayName {
            get {
                return ResourceManager.GetString("GetUser_UserId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get all the users in a group..
        /// </summary>
        public static string GetUsersOfGroup_Description {
            get {
                return ResourceManager.GetString("GetUsersOfGroup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Users Of Group.
        /// </summary>
        public static string GetUsersOfGroup_DisplayName {
            get {
                return ResourceManager.GetString("GetUsersOfGroup_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group identifier, as returned by the group creation API or retrieved from the API to fetch groups..
        /// </summary>
        public static string GetUsersOfGroup_GroupId_Description {
            get {
                return ResourceManager.GetString("GetUsersOfGroup_GroupId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Id.
        /// </summary>
        public static string GetUsersOfGroup_GroupId_DisplayName {
            get {
                return ResourceManager.GetString("GetUsersOfGroup_GroupId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetUsersOfGroup_GroupUsersInformation_Description {
            get {
                return ResourceManager.GetString("GetUsersOfGroup_GroupUsersInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Users Information.
        /// </summary>
        public static string GetUsersOfGroup_GroupUsersInformation_DisplayName {
            get {
                return ResourceManager.GetString("GetUsersOfGroup_GroupUsersInformation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the details of the workflow..
        /// </summary>
        public static string GetWorkflow_Description {
            get {
                return ResourceManager.GetString("GetWorkflow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Workflow.
        /// </summary>
        public static string GetWorkflow_DisplayName {
            get {
                return ResourceManager.GetString("GetWorkflow_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string GetWorkflow_WorkflowDescription_Description {
            get {
                return ResourceManager.GetString("GetWorkflow_WorkflowDescription_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Description.
        /// </summary>
        public static string GetWorkflow_WorkflowDescription_DisplayName {
            get {
                return ResourceManager.GetString("GetWorkflow_WorkflowDescription_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workflow identifier, as retrieved from the API to fetch workflows..
        /// </summary>
        public static string GetWorkflow_WorkflowId_Description {
            get {
                return ResourceManager.GetString("GetWorkflow_WorkflowId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Id.
        /// </summary>
        public static string GetWorkflow_WorkflowId_DisplayName {
            get {
                return ResourceManager.GetString("GetWorkflow_WorkflowId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity used to revoke the access as well as refresh tokens..
        /// </summary>
        public static string RevokeToken_Description {
            get {
                return ResourceManager.GetString("RevokeToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke Token.
        /// </summary>
        public static string RevokeToken_DisplayName {
            get {
                return ResourceManager.GetString("RevokeToken_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of the token revoked..
        /// </summary>
        public static string RevokeToken_Status_Description {
            get {
                return ResourceManager.GetString("RevokeToken_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string RevokeToken_Status_DisplayName {
            get {
                return ResourceManager.GetString("RevokeToken_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates an agreement. Sends it out for signatures, and returns the Agreement Id in the response to the client..
        /// </summary>
        public static string SendAgreement_Description {
            get {
                return ResourceManager.GetString("SendAgreement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Agreement.
        /// </summary>
        public static string SendAgreement_DisplayName {
            get {
                return ResourceManager.GetString("SendAgreement_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Ids of recipients..
        /// </summary>
        public static string SendAgreement_EmailId_Description {
            get {
                return ResourceManager.GetString("SendAgreement_EmailId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id.
        /// </summary>
        public static string SendAgreement_EmailId_DisplayName {
            get {
                return ResourceManager.GetString("SendAgreement_EmailId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique identifier of the agreement..
        /// </summary>
        public static string SendAgreement_Id_Description {
            get {
                return ResourceManager.GetString("SendAgreement_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SendAgreement_Id_DisplayName {
            get {
                return ResourceManager.GetString("SendAgreement_Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the agreement that will be used to identify it, in emails, website and other places..
        /// </summary>
        public static string SendAgreement_Name_Description {
            get {
                return ResourceManager.GetString("SendAgreement_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SendAgreement_Name_DisplayName {
            get {
                return ResourceManager.GetString("SendAgreement_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role of the participant set..
        /// </summary>
        public static string SendAgreement_Role_Description {
            get {
                return ResourceManager.GetString("SendAgreement_Role_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string SendAgreement_Role_DisplayName {
            get {
                return ResourceManager.GetString("SendAgreement_Role_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of signature you would like to request..
        /// </summary>
        public static string SendAgreement_SignatureType_Description {
            get {
                return ResourceManager.GetString("SendAgreement_SignatureType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Type.
        /// </summary>
        public static string SendAgreement_SignatureType_DisplayName {
            get {
                return ResourceManager.GetString("SendAgreement_SignatureType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state in which the agreement should land..
        /// </summary>
        public static string SendAgreement_State_Description {
            get {
                return ResourceManager.GetString("SendAgreement_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string SendAgreement_State_DisplayName {
            get {
                return ResourceManager.GetString("SendAgreement_State_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique identifier of the uploaded document that can be used in an agreement..
        /// </summary>
        public static string SendAgreement_TransientDocumentId_Description {
            get {
                return ResourceManager.GetString("SendAgreement_TransientDocumentId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transient Document Id.
        /// </summary>
        public static string SendAgreement_TransientDocumentId_DisplayName {
            get {
                return ResourceManager.GetString("SendAgreement_TransientDocumentId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agreement identifier, as returned by the agreement creation API or retrieved from the API to fetch agreements..
        /// </summary>
        public static string SendReminder_AgreementId_Description {
            get {
                return ResourceManager.GetString("SendReminder_AgreementId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Id.
        /// </summary>
        public static string SendReminder_AgreementId_DisplayName {
            get {
                return ResourceManager.GetString("SendReminder_AgreementId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a reminder on the specified participants of an agreement identified by Agreement Id in the path..
        /// </summary>
        public static string SendReminder_Description {
            get {
                return ResourceManager.GetString("SendReminder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Reminder.
        /// </summary>
        public static string SendReminder_DisplayName {
            get {
                return ResourceManager.GetString("SendReminder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency at which reminder will be sent until the agreement is completed..
        /// </summary>
        public static string SendReminder_Frequency_Description {
            get {
                return ResourceManager.GetString("SendReminder_Frequency_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string SendReminder_Frequency_DisplayName {
            get {
                return ResourceManager.GetString("SendReminder_Frequency_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of one or more participant IDs that the reminder should be sent to..
        /// </summary>
        public static string SendReminder_ParticipantIds_Description {
            get {
                return ResourceManager.GetString("SendReminder_ParticipantIds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Ids.
        /// </summary>
        public static string SendReminder_ParticipantIds_DisplayName {
            get {
                return ResourceManager.GetString("SendReminder_ParticipantIds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string SendReminder_ReminderCreationResult_Description {
            get {
                return ResourceManager.GetString("SendReminder_ReminderCreationResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Creation Result.
        /// </summary>
        public static string SendReminder_ReminderCreationResult_DisplayName {
            get {
                return ResourceManager.GetString("SendReminder_ReminderCreationResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agreement identifier, as returned by the agreement creation API or retrieved from the API to fetch agreements..
        /// </summary>
        public static string ShareAgreement_AgreementId_Description {
            get {
                return ResourceManager.GetString("ShareAgreement_AgreementId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Id.
        /// </summary>
        public static string ShareAgreement_AgreementId_DisplayName {
            get {
                return ResourceManager.GetString("ShareAgreement_AgreementId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share an agreement with someone..
        /// </summary>
        public static string ShareAgreement_Description {
            get {
                return ResourceManager.GetString("ShareAgreement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Agreement.
        /// </summary>
        public static string ShareAgreement_DisplayName {
            get {
                return ResourceManager.GetString("ShareAgreement_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address of the member with whom the agreement will be shared..
        /// </summary>
        public static string ShareAgreement_EmailIds_Description {
            get {
                return ResourceManager.GetString("ShareAgreement_EmailIds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Ids.
        /// </summary>
        public static string ShareAgreement_EmailIds_DisplayName {
            get {
                return ResourceManager.GetString("ShareAgreement_EmailIds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional message to the sharee..
        /// </summary>
        public static string ShareAgreement_Message_Description {
            get {
                return ResourceManager.GetString("ShareAgreement_Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ShareAgreement_Message_DisplayName {
            get {
                return ResourceManager.GetString("ShareAgreement_Message_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Json..
        /// </summary>
        public static string ShareAgreement_ShareCreationResponseList_Description {
            get {
                return ResourceManager.GetString("ShareAgreement_ShareCreationResponseList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Creation Response List.
        /// </summary>
        public static string ShareAgreement_ShareCreationResponseList_DisplayName {
            get {
                return ResourceManager.GetString("ShareAgreement_ShareCreationResponseList_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agreement identifier, as returned by the agreement creation API or retrieved from the API to fetch agreements..
        /// </summary>
        public static string UpdateAgreementState_AgreementId_Description {
            get {
                return ResourceManager.GetString("UpdateAgreementState_AgreementId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Id.
        /// </summary>
        public static string UpdateAgreementState_AgreementId_DisplayName {
            get {
                return ResourceManager.GetString("UpdateAgreementState_AgreementId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the comment to update the state..
        /// </summary>
        public static string UpdateAgreementState_Comments_Description {
            get {
                return ResourceManager.GetString("UpdateAgreementState_Comments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string UpdateAgreementState_Comments_DisplayName {
            get {
                return ResourceManager.GetString("UpdateAgreementState_Comments_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the state of the agreement sent..
        /// </summary>
        public static string UpdateAgreementState_Description {
            get {
                return ResourceManager.GetString("UpdateAgreementState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Agreement State.
        /// </summary>
        public static string UpdateAgreementState_DisplayName {
            get {
                return ResourceManager.GetString("UpdateAgreementState_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set true if you want others to notify with updated state of the agreement else false..
        /// </summary>
        public static string UpdateAgreementState_NotifyOthers_Description {
            get {
                return ResourceManager.GetString("UpdateAgreementState_NotifyOthers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Others.
        /// </summary>
        public static string UpdateAgreementState_NotifyOthers_DisplayName {
            get {
                return ResourceManager.GetString("UpdateAgreementState_NotifyOthers_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Boolean..
        /// </summary>
        public static string UpdateAgreementState_Response_Description {
            get {
                return ResourceManager.GetString("UpdateAgreementState_Response_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string UpdateAgreementState_Response_DisplayName {
            get {
                return ResourceManager.GetString("UpdateAgreementState_Response_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the state to be updated..
        /// </summary>
        public static string UpdateAgreementState_State_Description {
            get {
                return ResourceManager.GetString("UpdateAgreementState_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string UpdateAgreementState_State_DisplayName {
            get {
                return ResourceManager.GetString("UpdateAgreementState_State_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agreement identifier, as returned by the agreement creation API or retrieved from the API to fetch agreements..
        /// </summary>
        public static string UpdateAgreementVisibility_AgreementId_Description {
            get {
                return ResourceManager.GetString("UpdateAgreementVisibility_AgreementId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Id.
        /// </summary>
        public static string UpdateAgreementVisibility_AgreementId_DisplayName {
            get {
                return ResourceManager.GetString("UpdateAgreementVisibility_AgreementId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the visibility of the any agreement..
        /// </summary>
        public static string UpdateAgreementVisibility_Description {
            get {
                return ResourceManager.GetString("UpdateAgreementVisibility_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Agreement Visibility.
        /// </summary>
        public static string UpdateAgreementVisibility_DisplayName {
            get {
                return ResourceManager.GetString("UpdateAgreementVisibility_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Boolean..
        /// </summary>
        public static string UpdateAgreementVisibility_Response_Description {
            get {
                return ResourceManager.GetString("UpdateAgreementVisibility_Response_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string UpdateAgreementVisibility_Response_DisplayName {
            get {
                return ResourceManager.GetString("UpdateAgreementVisibility_Response_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the visibility status..
        /// </summary>
        public static string UpdateAgreementVisibility_VisibilityStatus_Description {
            get {
                return ResourceManager.GetString("UpdateAgreementVisibility_VisibilityStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Status.
        /// </summary>
        public static string UpdateAgreementVisibility_VisibilityStatus_DisplayName {
            get {
                return ResourceManager.GetString("UpdateAgreementVisibility_VisibilityStatus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates the library document&apos;s state..
        /// </summary>
        public static string UpdateLibraryDocumentState_Description {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Library Document State.
        /// </summary>
        public static string UpdateLibraryDocumentState_DisplayName {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentState_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document identifier, as retrieved from the API to fetch library documents..
        /// </summary>
        public static string UpdateLibraryDocumentState_LibraryDocumentId_Description {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentState_LibraryDocumentId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Document Id.
        /// </summary>
        public static string UpdateLibraryDocumentState_LibraryDocumentId_DisplayName {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentState_LibraryDocumentId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Boolean..
        /// </summary>
        public static string UpdateLibraryDocumentState_Response_Description {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentState_Response_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string UpdateLibraryDocumentState_Response_DisplayName {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentState_Response_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the state to be updated..
        /// </summary>
        public static string UpdateLibraryDocumentState_State_Description {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentState_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string UpdateLibraryDocumentState_State_DisplayName {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentState_State_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates the visibility of library document..
        /// </summary>
        public static string UpdateLibraryDocumentVisibility_Description {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentVisibility_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Library Document Visibility.
        /// </summary>
        public static string UpdateLibraryDocumentVisibility_DisplayName {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentVisibility_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document identifier, as retrieved from the API to fetch library documents..
        /// </summary>
        public static string UpdateLibraryDocumentVisibility_LibraryDocumentId_Description {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentVisibility_LibraryDocumentId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Document Id.
        /// </summary>
        public static string UpdateLibraryDocumentVisibility_LibraryDocumentId_DisplayName {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentVisibility_LibraryDocumentId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Boolean..
        /// </summary>
        public static string UpdateLibraryDocumentVisibility_Response_Description {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentVisibility_Response_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string UpdateLibraryDocumentVisibility_Response_DisplayName {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentVisibility_Response_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the visibility status..
        /// </summary>
        public static string UpdateLibraryDocumentVisibility_VisibilityStatus_Description {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentVisibility_VisibilityStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Status.
        /// </summary>
        public static string UpdateLibraryDocumentVisibility_VisibilityStatus_DisplayName {
            get {
                return ResourceManager.GetString("UpdateLibraryDocumentVisibility_VisibilityStatus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update some of the details of the user..
        /// </summary>
        public static string UpdateUserDetails_Description {
            get {
                return ResourceManager.GetString("UpdateUserDetails_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User Details.
        /// </summary>
        public static string UpdateUserDetails_DisplayName {
            get {
                return ResourceManager.GetString("UpdateUserDetails_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set true or false if you want to user to create admin..
        /// </summary>
        public static string UpdateUserDetails_IsAccountAdmin_Description {
            get {
                return ResourceManager.GetString("UpdateUserDetails_IsAccountAdmin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Account Admin.
        /// </summary>
        public static string UpdateUserDetails_IsAccountAdmin_DisplayName {
            get {
                return ResourceManager.GetString("UpdateUserDetails_IsAccountAdmin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone number to update..
        /// </summary>
        public static string UpdateUserDetails_Phone_Description {
            get {
                return ResourceManager.GetString("UpdateUserDetails_Phone_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string UpdateUserDetails_Phone_DisplayName {
            get {
                return ResourceManager.GetString("UpdateUserDetails_Phone_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Boolean..
        /// </summary>
        public static string UpdateUserDetails_Reponse_Description {
            get {
                return ResourceManager.GetString("UpdateUserDetails_Reponse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string UpdateUserDetails_Reponse_DisplayName {
            get {
                return ResourceManager.GetString("UpdateUserDetails_Reponse_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title to update..
        /// </summary>
        public static string UpdateUserDetails_Title_Description {
            get {
                return ResourceManager.GetString("UpdateUserDetails_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string UpdateUserDetails_Title_DisplayName {
            get {
                return ResourceManager.GetString("UpdateUserDetails_Title_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id of an user..
        /// </summary>
        public static string UpdateUserDetails_UserId_Description {
            get {
                return ResourceManager.GetString("UpdateUserDetails_UserId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UpdateUserDetails_UserId_DisplayName {
            get {
                return ResourceManager.GetString("UpdateUserDetails_UserId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the comment to update the state..
        /// </summary>
        public static string UpdateUserState_Comments_Description {
            get {
                return ResourceManager.GetString("UpdateUserState_Comments_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string UpdateUserState_Comments_DisplayName {
            get {
                return ResourceManager.GetString("UpdateUserState_Comments_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the state of the user..
        /// </summary>
        public static string UpdateUserState_Description {
            get {
                return ResourceManager.GetString("UpdateUserState_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User State.
        /// </summary>
        public static string UpdateUserState_DisplayName {
            get {
                return ResourceManager.GetString("UpdateUserState_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response in Boolean..
        /// </summary>
        public static string UpdateUserState_Response_Description {
            get {
                return ResourceManager.GetString("UpdateUserState_Response_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string UpdateUserState_Response_DisplayName {
            get {
                return ResourceManager.GetString("UpdateUserState_Response_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the state to be updated..
        /// </summary>
        public static string UpdateUserState_State_Description {
            get {
                return ResourceManager.GetString("UpdateUserState_State_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string UpdateUserState_State_DisplayName {
            get {
                return ResourceManager.GetString("UpdateUserState_State_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id of an user..
        /// </summary>
        public static string UpdateUserState_UserId_Description {
            get {
                return ResourceManager.GetString("UpdateUserState_UserId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string UpdateUserState_UserId_DisplayName {
            get {
                return ResourceManager.GetString("UpdateUserState_UserId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
